/**
 * Dashboard summary.
 *
 * Aggregates connection state, review counts, draft counts and the automation
 * run log into the cards on the overview page. Designed never to fail: a
 * Google outage degrades individual numbers rather than breaking the page.
 */

import { configWarnings } from '@/lib/config';
import { resolveTarget } from '@/lib/connection';
import { AppError, isApprovalPending } from '@/lib/errors';
import { listReviews } from '@/lib/google-business';
import { getRefreshToken } from '@/lib/google-auth';
import {
  getCachedReviews,
  listDrafts,
  listPosts,
  listRuns,
  getSettings,
} from '@/lib/repository';
import { assertAdmin, handleRoute, ok } from '@/lib/security';
import { applyDraftStatus } from '@/lib/tasks';
import type { DashboardSummary, Review } from '@/lib/types';

export const dynamic = 'force-dynamic';
export const runtime = 'nodejs';

/** Reviews created in the last 7 days. */
function countRecent(reviews: Review[]): number {
  const cutoff = Date.now() - 7 * 24 * 60 * 60 * 1000;
  return reviews.filter((r) => new Date(r.createTime).getTime() >= cutoff).length;
}

export async function GET(request: Request) {
  return handleRoute('status', async () => {
    assertAdmin(request);

    const [drafts, posts, runs, settings, refreshToken] = await Promise.all([
      listDrafts(),
      listPosts(),
      listRuns(),
      getSettings(),
      getRefreshToken().catch(() => null),
    ]);

    let reviews: Review[] = [];
    let averageRating: number | null = null;
    let totalReviews = 0;
    let connectionLabel = 'Not connected';
    let connectionDetail = 'Connect a Google account to start pulling reviews.';
    let connected = false;

    if (!refreshToken) {
      connectionLabel = 'Not connected';
      connectionDetail = 'No Google account is linked yet.';
    } else {
      try {
        const target = await resolveTarget();
        const result = await listReviews(target.locationPath, { maxPages: 2 });
        reviews = applyDraftStatus(result.reviews, drafts);
        averageRating = result.averageRating;
        totalReviews = result.totalReviewCount;
        connected = true;
        connectionLabel = 'Connected';
        connectionDetail = target.locationPath;
      } catch (error) {
        const cached = await getCachedReviews();
        if (cached) {
          reviews = applyDraftStatus(cached.reviews, drafts);
          averageRating = cached.averageRating;
          totalReviews = cached.totalReviewCount;
        }
        if (error instanceof AppError && isApprovalPending(error.code)) {
          connectionLabel = 'Approval pending';
          connectionDetail = 'Google Business Profile API approval pending.';
        } else {
          connectionLabel = 'Connection problem';
          connectionDetail =
            error instanceof AppError ? error.message : 'Unexpected error contacting Google.';
        }
      }
    }

    const summary: DashboardSummary = {
      connection: { connected, label: connectionLabel, detail: connectionDetail },
      newReviews: countRecent(reviews),
      unansweredReviews: reviews.filter((r) => !r.existingReply).length,
      pendingDrafts: drafts.filter((d) => d.status === 'draft_pending').length,
      approvedDrafts: drafts.filter((d) => d.status === 'approved').length,
      scheduledPosts: posts.filter((p) => p.status === 'scheduled').length,
      publishedPosts: posts.filter((p) => p.status === 'published').length,
      averageRating,
      totalReviews: totalReviews || reviews.length,
      automation: {
        enabled: settings.autoGenerateDrafts,
        lastRuns: runs.slice(0, 8),
      },
      warnings: configWarnings(refreshToken),
    };

    return ok(summary);
  });
}
