'use client';

/**
 * Settings.
 *
 * Every environment variable is reported as configured / not configured only.
 * No secret value is ever fetched or rendered.
 */

import { useRouter } from 'next/navigation';
import { useCallback, useEffect, useState } from 'react';

import { api, ApiError } from '@/lib/client';
import {
  Alert,
  Badge,
  Button,
  Card,
  CardHeader,
  LoadingCard,
  PageHeading,
} from '@/components/ui';

type Payload = {
  settings: {
    autoPublishReplies: boolean;
    autoGenerateDrafts: boolean;
    autoDraftMinStars: number;
    selectedAccount?: string;
    selectedLocation?: string;
  };
  config: {
    business: { name: string; website: string };
    oauthConfigured: boolean;
    googleConfigured: boolean;
    aiConfigured: boolean;
    cronConfigured: boolean;
    adminAuthConfigured: boolean;
    durableStore: boolean;
    autoPublishReplies: boolean;
    pinnedLocation: boolean;
    environment: string;
  };
  warnings: string[];
  business: { name: string; website: string; services: string[] };
};

function Toggle({
  label,
  description,
  checked,
  onChange,
  disabled,
  warn,
}: {
  label: string;
  description: string;
  checked: boolean;
  onChange: (value: boolean) => void;
  disabled?: boolean;
  warn?: boolean;
}) {
  return (
    <div className="flex items-start justify-between gap-4 py-3">
      <div className="min-w-0">
        <p className="text-sm font-medium text-ink-900">{label}</p>
        <p className="mt-0.5 text-sm text-ink-500">{description}</p>
      </div>
      <button
        type="button"
        role="switch"
        aria-checked={checked}
        aria-label={label}
        disabled={disabled}
        onClick={() => onChange(!checked)}
        className={`relative mt-0.5 h-6 w-11 shrink-0 rounded-full transition-colors disabled:opacity-50 ${
          checked ? (warn ? 'bg-gold-500' : 'bg-brand-600') : 'bg-ink-300'
        }`}
      >
        <span
          className={`absolute top-0.5 h-5 w-5 rounded-full bg-white transition-transform ${
            checked ? 'translate-x-5.5' : 'translate-x-0.5'
          }`}
        />
      </button>
    </div>
  );
}

function ConfigRow({ label, ready, note }: { label: string; ready: boolean; note: string }) {
  return (
    <li className="flex flex-wrap items-center justify-between gap-2 py-2.5">
      <div className="min-w-0">
        <code className="text-sm text-ink-900">{label}</code>
        <p className="text-xs text-ink-500">{note}</p>
      </div>
      <Badge tone={ready ? 'ok' : 'warn'}>{ready ? 'Configured' : 'Not set'}</Badge>
    </li>
  );
}

export default function SettingsClient() {
  const router = useRouter();
  const [payload, setPayload] = useState<Payload | null>(null);
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [flash, setFlash] = useState<string | null>(null);

  const load = useCallback(async () => {
    try {
      const response = await api.get<Payload>('/api/settings');
      setPayload(response.data);
    } catch (caught) {
      setError(caught instanceof ApiError ? caught.message : 'Could not load settings.');
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    void load();
  }, [load]);

  async function patch(update: Record<string, unknown>) {
    setBusy(true);
    setError(null);
    setFlash(null);
    try {
      const response = await api.patch<{ settings: Payload['settings'] }>('/api/settings', update);
      setFlash(response.message);
      await load();
    } catch (caught) {
      setError(caught instanceof ApiError ? caught.message : 'Could not save settings.');
    } finally {
      setBusy(false);
    }
  }

  async function signOut() {
    await fetch('/api/auth/logout', { method: 'POST' });
    router.replace('/login');
    router.refresh();
  }

  return (
    <>
      <PageHeading title="Settings" description="Automation behaviour and configuration status" />

      {error ? (
        <div className="mb-4">
          <Alert tone="danger" title="Problem">
            <p>{error}</p>
          </Alert>
        </div>
      ) : null}
      {flash ? (
        <div className="mb-4">
          <Alert tone="ok" title="Saved">
            <p>{flash}</p>
          </Alert>
        </div>
      ) : null}

      {loading && !payload ? <LoadingCard lines={4} /> : null}

      {payload ? (
        <>
          <Card className="mb-4">
            <CardHeader title="Automation" description="These take effect on the next cron run" />
            <div className="divide-y divide-hairline">
              <Toggle
                label="Generate reply drafts automatically"
                description="When cron finds an unanswered review, draft a reply for it."
                checked={payload.settings.autoGenerateDrafts}
                disabled={busy || !payload.config.aiConfigured}
                onChange={(value) => void patch({ autoGenerateDrafts: value })}
              />
              <Toggle
                label="Publish approved replies automatically"
                description="Off by design. Turning this on lets cron publish approved drafts without a final human check."
                checked={payload.settings.autoPublishReplies}
                disabled={busy}
                warn
                onChange={(value) => void patch({ autoPublishReplies: value })}
              />
            </div>

            <div className="mt-3 border-t border-hairline pt-3">
              <label
                htmlFor="min-stars"
                className="mb-1.5 block text-sm font-medium text-ink-900"
              >
                Only auto-draft for reviews rated at least
              </label>
              <select
                id="min-stars"
                value={payload.settings.autoDraftMinStars}
                disabled={busy}
                onChange={(event) =>
                  void patch({ autoDraftMinStars: Number(event.target.value) })
                }
                className="w-full rounded-xl border border-hairline bg-surface px-3.5 py-2.5 text-ink-900 outline-none focus:border-brand-500 sm:max-w-xs"
              >
                {[1, 2, 3, 4, 5].map((stars) => (
                  <option key={stars} value={stars}>
                    {stars}★ and above
                  </option>
                ))}
              </select>
            </div>

            {!payload.config.aiConfigured ? (
              <p className="mt-3 text-xs text-warn-700">
                OPENAI_API_KEY is not set, so drafting is disabled regardless of this switch.
              </p>
            ) : null}
          </Card>

          <Card className="mb-4">
            <CardHeader
              title="Configuration"
              description="Status only — values are never read by the browser"
            />
            <ul className="divide-y divide-hairline">
              <ConfigRow
                label="GOOGLE_CLIENT_ID / SECRET / REDIRECT_URI"
                ready={payload.config.oauthConfigured}
                note="OAuth client for the business.manage scope"
              />
              <ConfigRow
                label="GOOGLE_REFRESH_TOKEN"
                ready={payload.config.googleConfigured}
                note="Long-lived credential for the connected Business Profile"
              />
              <ConfigRow
                label="OPENAI_API_KEY"
                ready={payload.config.aiConfigured}
                note="Required for AI reply drafting"
              />
              <ConfigRow
                label="CRON_SECRET"
                ready={payload.config.cronConfigured}
                note="Protects every /api/cron endpoint"
              />
              <ConfigRow
                label="ADMIN_PASSWORD / SESSION_SECRET"
                ready={payload.config.adminAuthConfigured}
                note="Locks this dashboard and all write APIs"
              />
              <ConfigRow
                label="UPSTASH_REDIS_REST_URL / TOKEN"
                ready={payload.config.durableStore}
                note="Durable storage for drafts, posts and the run log"
              />
              <ConfigRow
                label="GBP_ACCOUNT_NAME / GBP_LOCATION_NAME"
                ready={payload.config.pinnedLocation}
                note="Optional — pins the location instead of auto-detecting it"
              />
            </ul>
            <p className="mt-3 text-xs text-ink-500">
              Environment: {payload.config.environment}
            </p>
          </Card>

          <Card className="mb-4">
            <CardHeader title="Business" description="Used to ground AI reply drafts" />
            <p className="text-sm text-ink-900">{payload.business.name}</p>
            <a
              href={payload.business.website}
              target="_blank"
              rel="noreferrer noopener"
              className="text-sm text-brand-700 underline underline-offset-2"
            >
              {payload.business.website}
            </a>
            <div className="mt-3 flex flex-wrap gap-1.5">
              {payload.business.services.map((service) => (
                <Badge key={service}>{service}</Badge>
              ))}
            </div>
          </Card>

          {payload.warnings.length > 0 ? (
            <div className="mb-4">
              <Alert tone="warn" title="Still to do">
                <ul className="mt-1 list-disc space-y-1 pl-5">
                  {payload.warnings.map((warning) => (
                    <li key={warning}>{warning}</li>
                  ))}
                </ul>
              </Alert>
            </div>
          ) : null}

          {payload.config.adminAuthConfigured ? (
            <Card>
              <CardHeader title="Session" />
              <Button variant="secondary" onClick={() => void signOut()}>
                Sign out
              </Button>
            </Card>
          ) : null}
        </>
      ) : null}
    </>
  );
}
