'use client';

/**
 * Settings.
 *
 * Every environment variable is reported as configured / not configured only.
 * No secret value is ever fetched or rendered.
 */

import { useRouter } from 'next/navigation';
import { useCallback, useEffect, useState } from 'react';

import { api, ApiError, relativeTime } from '@/lib/client';
import {
  AlertIcon,
  CheckCircleIcon,
  ExternalIcon,
  LogoutIcon,
  RefreshIcon,
  SettingsIcon,
  ShieldIcon,
  SparkIcon,
} from '@/components/icons';
import { AccessServiceList, CheckAccessButton } from '@/components/gbp-access-panel';
import {
  Badge,
  Button,
  ButtonLink,
  Callout,
  Card,
  PageHeader,
  SectionHeader,
  SkeletonCard,
  type Tone,
} from '@/components/ui';
import { ACCESS_LABEL, type GbpAccessSnapshot } from '@/lib/gbp-status';

type Payload = {
  settings: {
    autoPublishReplies: boolean;
    autoGenerateDrafts: boolean;
    autoDraftMinStars: number;
    selectedAccount?: string;
    selectedLocation?: string;
  };
  config: {
    business: { name: string; website: string };
    oauthConfigured: boolean;
    googleConfigured: boolean;
    aiConfigured: boolean;
    aiProviderOrder: string[];
    aiProvidersConfigured: Record<string, boolean>;
    aiModels: Record<string, string>;
    cronConfigured: boolean;
    adminAuthConfigured: boolean;
    durableStore: boolean;
    autoPublishReplies: boolean;
    pinnedLocation: boolean;
    environment: string;
    mockMode: boolean;
  };
  warnings: string[];
  business: { name: string; website: string; services: string[] };
  credential: {
    connected: boolean;
    source: 'stored' | 'environment' | null;
    environmentTokenIgnored: boolean;
  };
  /** The shared access snapshot — the same one the dashboard and Connection page read. */
  gbpAccess: GbpAccessSnapshot;
};

function Toggle({
  id,
  label,
  description,
  checked,
  onChange,
  disabled,
  warn,
}: {
  id: string;
  label: string;
  description: string;
  checked: boolean;
  onChange: (value: boolean) => void;
  disabled?: boolean;
  warn?: boolean;
}) {
  return (
    <div className="flex items-start justify-between gap-4 py-4 first:pt-0 last:pb-0">
      <div className="min-w-0">
        <label htmlFor={id} className="text-sm font-medium text-ink-900">
          {label}
        </label>
        <p className="mt-0.5 text-[0.8125rem] leading-relaxed text-ink-500">{description}</p>
      </div>
      <button
        id={id}
        type="button"
        role="switch"
        aria-checked={checked}
        disabled={disabled}
        onClick={() => onChange(!checked)}
        className={`relative mt-0.5 h-6 w-11 shrink-0 rounded-full transition-colors duration-200 after:absolute after:-inset-y-2.5 after:-inset-x-1 after:content-[''] disabled:opacity-50 ${
          checked ? (warn ? 'bg-warning-600' : 'bg-brand-600') : 'bg-ink-300'
        }`}
      >
        <span
          className={`absolute top-0.5 h-5 w-5 rounded-full bg-white shadow-xs transition-transform duration-200 ${
            checked ? 'translate-x-[1.375rem]' : 'translate-x-0.5'
          }`}
        />
      </button>
    </div>
  );
}

function ConfigRow({ label, ready, note }: { label: string; ready: boolean; note: string }) {
  return (
    <li className="flex flex-wrap items-center justify-between gap-x-3 gap-y-1.5 py-3 first:pt-0 last:pb-0">
      <div className="min-w-0 flex-1">
        <code className="text-[0.8125rem] font-medium text-ink-800">{label}</code>
        <p className="mt-0.5 text-xs leading-relaxed text-ink-500">{note}</p>
      </div>
      <Badge tone={ready ? 'success' : 'warning'} dot>
        {ready ? 'Configured' : 'Not set'}
      </Badge>
    </li>
  );
}

const PROVIDER_LABELS: Record<string, string> = {
  groq: 'Groq',
  gemini: 'Gemini',
  openai: 'OpenAI',
};

export default function SettingsClient() {
  const router = useRouter();
  const [payload, setPayload] = useState<Payload | null>(null);
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [flash, setFlash] = useState<string | null>(null);

  const load = useCallback(async () => {
    try {
      const response = await api.get<Payload>('/api/settings');
      setPayload(response.data);
      setError(null);
    } catch (caught) {
      setError(caught instanceof ApiError ? caught.message : 'Could not load your settings.');
    } finally {
      setLoading(false);
    }
  }, []);

  const refresh = useCallback(() => {
    setLoading(true);
    void load();
  }, [load]);

  useEffect(() => {
    void load();
  }, [load]);

  async function patch(update: Record<string, unknown>) {
    setBusy(true);
    setError(null);
    setFlash(null);
    try {
      const response = await api.patch<{ settings: Payload['settings'] }>('/api/settings', update);
      setFlash(response.message);
      await load();
    } catch (caught) {
      setError(caught instanceof ApiError ? caught.message : 'Could not save that change.');
    } finally {
      setBusy(false);
    }
  }

  /** True only when Google has actually answered (or mock mode stands in). */
  const googleWorking =
    payload?.config.mockMode === true || payload?.gbpAccess.status === 'available';

  async function signOut() {
    await api.post('/api/auth/logout').catch(() => undefined);
    router.replace('/login');
    router.refresh();
  }

  return (
    <>
      <PageHeader
        eyebrow="Configuration"
        title="Settings"
        description="How the automation behaves, and what is still waiting to be set up."
        action={
          <Button variant="secondary" onClick={refresh} loading={loading} icon={<RefreshIcon size={16} />}>
            Refresh
          </Button>
        }
      />

      {error ? (
        <div className="mb-4">
          <Callout tone="danger" title="Something went wrong">
            <p>{error}</p>
          </Callout>
        </div>
      ) : null}
      {flash ? (
        <div className="mb-4">
          <Callout tone="success" title="Saved" icon={<CheckCircleIcon size={18} />}>
            <p>{flash}</p>
          </Callout>
        </div>
      ) : null}

      {loading && !payload ? <SkeletonCard lines={5} /> : null}

      {payload ? (
        <div className="space-y-5">
          {payload.warnings.length > 0 || !googleWorking ? (
            <Callout tone="warning" title="Still to set up" icon={<AlertIcon size={18} />}>
              <ul className="mt-1 list-disc space-y-1.5 pl-5">
                {payload.warnings.map((warning) => (
                  <li key={warning}>{warning}</li>
                ))}
                {!googleWorking && payload.config.googleConfigured ? (
                  <li>{payload.gbpAccess.message}</li>
                ) : null}
              </ul>
            </Callout>
          ) : (
            <Callout tone="success" title="Everything is configured" icon={<CheckCircleIcon size={18} />}>
              <p>No outstanding setup steps. Your automation is running end to end.</p>
            </Callout>
          )}

          <Card>
            <SectionHeader
              title="Automation"
              description="These take effect on the next scheduled run"
              icon={<SparkIcon size={18} />}
              tone="ai"
            />
            <div className="divide-y divide-line">
              <Toggle
                id="auto-drafts"
                label="Draft replies automatically"
                description="When a sync finds a review without a reply, write a draft for it. You still approve every one."
                checked={payload.settings.autoGenerateDrafts}
                disabled={busy || !payload.config.aiConfigured}
                onChange={(value) => void patch({ autoGenerateDrafts: value })}
              />
              <Toggle
                id="auto-publish"
                label="Publish approved replies automatically"
                description={
                  payload.config.autoPublishReplies
                    ? 'Off by design. Turning this on lets scheduled jobs publish approved drafts without a final look from you.'
                    : 'Locked off. AUTO_PUBLISH_REPLIES is false in the environment, so replies are only ever published when you press Publish. Set it to true in Vercel (and redeploy) to allow this switch.'
                }
                checked={payload.config.autoPublishReplies && payload.settings.autoPublishReplies}
                disabled={busy || !payload.config.autoPublishReplies}
                warn
                onChange={(value) => void patch({ autoPublishReplies: value })}
              />
            </div>

            <div className="mt-4 border-t border-line pt-4">
              <label htmlFor="min-stars" className="mb-1.5 block text-sm font-medium text-ink-900">
                Only draft replies for reviews rated
              </label>
              <select
                id="min-stars"
                value={payload.settings.autoDraftMinStars}
                disabled={busy}
                onChange={(event) => void patch({ autoDraftMinStars: Number(event.target.value) })}
                className="w-full rounded-xl border border-line bg-surface px-3.5 py-2.5 text-ink-900 outline-none transition-colors focus:border-brand-500 sm:max-w-xs"
              >
                {[1, 2, 3, 4, 5].map((stars) => (
                  <option key={stars} value={stars}>
                    {stars}★ and above
                  </option>
                ))}
              </select>
            </div>

            <div className="mt-4 border-t border-line pt-4">
              <div className="mb-2.5 flex flex-wrap items-center justify-between gap-2">
                <p className="text-[0.6875rem] font-semibold uppercase tracking-[0.06em] text-ink-400">
                  AI providers
                </p>
                <span className="text-xs text-ink-500">
                  Order:{' '}
                  {payload.config.aiProviderOrder
                    .map((name) => PROVIDER_LABELS[name] ?? name)
                    .join(' → ')}
                </span>
              </div>

              <ul className="divide-y divide-line">
                {payload.config.aiProviderOrder.map((name, index) => {
                  const configured = payload.config.aiProvidersConfigured[name] ?? false;
                  return (
                    <li key={name} className="flex flex-wrap items-center gap-x-3 gap-y-1 py-2.5">
                      <span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-md bg-subtle text-[0.6875rem] font-semibold text-ink-500">
                        {index + 1}
                      </span>
                      <span className="text-[0.875rem] font-medium text-ink-900">
                        {PROVIDER_LABELS[name] ?? name}
                      </span>
                      <code className="min-w-0 truncate text-xs text-ink-500">
                        {payload.config.aiModels[name]}
                      </code>
                      <Badge tone={configured ? 'success' : 'neutral'} dot className="ml-auto">
                        {configured ? 'Configured' : 'Not configured'}
                      </Badge>
                    </li>
                  );
                })}
              </ul>
              <p className="mt-2 text-xs leading-relaxed text-ink-400">
                Order is set by <code>AI_PROVIDER_ORDER</code> in the environment. Keys are never
                displayed here.
              </p>
            </div>

            {!payload.config.aiConfigured ? (
              <p className="mt-3 rounded-xl bg-warning-50 px-3.5 py-2.5 text-xs leading-relaxed text-warning-700">
                No AI provider is configured, so drafting is unavailable regardless of these
                switches.
              </p>
            ) : null}
          </Card>

          <Card>
            <SectionHeader
              title="Google Business Profile"
              description="Account link and API access are tracked separately"
              icon={<ShieldIcon size={18} />}
              tone="brand"
            />
            <dl className="divide-y divide-line">
              {[
                {
                  term: 'Google OAuth',
                  value: payload.config.oauthConfigured ? 'Configured' : 'Not configured',
                  tone: payload.config.oauthConfigured ? ('success' as const) : ('warning' as const),
                },
                {
                  term: 'Google account',
                  value: payload.config.googleConfigured
                    ? payload.gbpAccess.status === 'auth_error'
                      ? 'Reconnect needed'
                      : 'Connected'
                    : 'Not connected',
                  tone: !payload.config.googleConfigured
                    ? ('neutral' as const)
                    : payload.gbpAccess.status === 'auth_error'
                      ? ('danger' as const)
                      : ('success' as const),
                },
                {
                  term: 'GBP API access',
                  value: payload.config.googleConfigured
                    ? ACCESS_LABEL[payload.gbpAccess.status].label
                    : 'Not connected',
                  tone: (payload.config.googleConfigured
                    ? ACCESS_LABEL[payload.gbpAccess.status].tone
                    : 'neutral') as Tone,
                },
                {
                  term: 'Location',
                  value: !googleWorking
                    ? 'Waiting for API access'
                    : payload.config.pinnedLocation
                      ? 'Pinned by environment'
                      : payload.settings.selectedLocation
                        ? 'Chosen in dashboard'
                        : 'Auto-detected',
                  tone: 'neutral' as const,
                },
              ].map((row) => (
                <div
                  key={row.term}
                  className="flex flex-wrap items-center justify-between gap-2 py-2.5 first:pt-0 last:pb-0"
                >
                  <dt className="text-[0.875rem] text-ink-700">{row.term}</dt>
                  <dd>
                    <Badge tone={row.tone} dot>
                      {row.value}
                    </Badge>
                  </dd>
                </div>
              ))}
            </dl>
            <p className="mt-3 border-t border-line pt-3 text-xs leading-relaxed text-ink-500">
              {payload.config.googleConfigured ? payload.gbpAccess.message : 'No Google account is connected yet.'}
              {payload.gbpAccess.lastSuccessAt
                ? ` Last answered ${relativeTime(payload.gbpAccess.lastSuccessAt)}.`
                : ''}
            </p>

            {payload.config.googleConfigured ? (
              <>
                <div className="mt-4 border-t border-line pt-4">
                  <AccessServiceList access={payload.gbpAccess} />
                </div>
                <div className="mt-4 flex flex-wrap gap-2">
                  <CheckAccessButton
                    onChecked={(_, message) => {
                      setError(null);
                      setFlash(message);
                      void load();
                    }}
                    onError={(message) => {
                      setFlash(null);
                      setError(message);
                    }}
                  />
                  <ButtonLink href="/dashboard/connection" variant="ghost">
                    Manage connection
                  </ButtonLink>
                </div>
              </>
            ) : (
              <div className="mt-4">
                <ButtonLink href="/dashboard/connection">
                  {payload.config.oauthConfigured ? 'Connect Google' : 'View setup'}
                </ButtonLink>
              </div>
            )}
          </Card>

          <Card>
            <SectionHeader
              title="Configuration"
              description="Status only — no value is ever sent to your browser"
              icon={<ShieldIcon size={18} />}
              tone="brand"
              action={<Badge tone="neutral">{payload.config.environment}</Badge>}
            />
            <ul className="divide-y divide-line">
              <ConfigRow
                label="GOOGLE_CLIENT_ID / SECRET / REDIRECT_URI"
                ready={payload.config.oauthConfigured}
                note="OAuth client for the business.manage scope"
              />
              <ConfigRow
                label="Google refresh token"
                ready={payload.config.googleConfigured}
                note={
                  payload.credential.source === 'stored'
                    ? 'Saved by Connect Google (takes priority over GOOGLE_REFRESH_TOKEN)'
                    : payload.credential.source === 'environment'
                      ? 'From GOOGLE_REFRESH_TOKEN in the environment'
                      : payload.credential.environmentTokenIgnored
                        ? 'Disconnected — GOOGLE_REFRESH_TOKEN is set but ignored'
                        : 'Saved by Connect Google, or set GOOGLE_REFRESH_TOKEN'
                }
              />
              <ConfigRow
                label="GROQ_API_KEY"
                ready={payload.config.aiProvidersConfigured.groq ?? false}
                note="Primary AI provider for reply drafting"
              />
              <ConfigRow
                label="GEMINI_API_KEY"
                ready={payload.config.aiProvidersConfigured.gemini ?? false}
                note="Optional fallback provider"
              />
              <ConfigRow
                label="OPENAI_API_KEY"
                ready={payload.config.aiProvidersConfigured.openai ?? false}
                note="Optional third fallback"
              />
              <ConfigRow
                label="CRON_SECRET"
                ready={payload.config.cronConfigured}
                note="Protects every scheduled job endpoint"
              />
              <ConfigRow
                label="ADMIN_PASSWORD / SESSION_SECRET"
                ready={payload.config.adminAuthConfigured}
                note="Locks this dashboard and all write APIs"
              />
              <ConfigRow
                label="UPSTASH_REDIS_REST_URL / TOKEN"
                ready={payload.config.durableStore}
                note="Durable storage for drafts, posts and the run log"
              />
              <ConfigRow
                label="GBP_ACCOUNT_NAME / GBP_LOCATION_NAME"
                ready={payload.config.pinnedLocation}
                note="Optional — pins the location instead of auto-detecting it"
              />
            </ul>
          </Card>

          <Card>
            <SectionHeader
              title="Business"
              description="Used to ground the tone and wording of AI reply drafts"
              icon={<SettingsIcon size={18} />}
              tone="neutral"
            />
            <div className="flex flex-wrap items-center justify-between gap-3">
              <div className="min-w-0">
                <p className="text-sm font-semibold text-ink-950">{payload.business.name}</p>
                <a
                  href={payload.business.website}
                  target="_blank"
                  rel="noreferrer noopener"
                  className="-ml-2 inline-flex min-h-9 items-center gap-1 rounded-lg px-2 text-[0.8125rem] text-brand-700 hover:bg-brand-50"
                >
                  {payload.business.website.replace(/^https?:\/\//, '')}
                  <ExternalIcon size={13} />
                </a>
              </div>
            </div>
            <div className="mt-4 flex flex-wrap gap-1.5 border-t border-line pt-4">
              {payload.business.services.map((service) => (
                <Badge key={service} tone="neutral">
                  {service}
                </Badge>
              ))}
            </div>
          </Card>

          {payload.config.adminAuthConfigured ? (
            <Card>
              <SectionHeader title="Session" description="You are signed in as the administrator" />
              <Button variant="secondary" icon={<LogoutIcon size={16} />} onClick={() => void signOut()}>
                Sign out
              </Button>
            </Card>
          ) : null}
        </div>
      ) : null}
    </>
  );
}

