'use client';

/**
 * Settings.
 *
 * Every environment variable is reported as configured / not configured only.
 * No secret value is ever fetched or rendered.
 */

import { useRouter } from 'next/navigation';
import { useCallback, useEffect, useState } from 'react';

import { api, ApiError } from '@/lib/client';
import {
  AlertIcon,
  CheckCircleIcon,
  ExternalIcon,
  LogoutIcon,
  RefreshIcon,
  SettingsIcon,
  ShieldIcon,
  SparkIcon,
} from '@/components/icons';
import {
  Badge,
  Button,
  Callout,
  Card,
  PageHeader,
  SectionHeader,
  SkeletonCard,
} from '@/components/ui';

type Payload = {
  settings: {
    autoPublishReplies: boolean;
    autoGenerateDrafts: boolean;
    autoDraftMinStars: number;
    selectedAccount?: string;
    selectedLocation?: string;
  };
  config: {
    business: { name: string; website: string };
    oauthConfigured: boolean;
    googleConfigured: boolean;
    aiConfigured: boolean;
    cronConfigured: boolean;
    adminAuthConfigured: boolean;
    durableStore: boolean;
    autoPublishReplies: boolean;
    pinnedLocation: boolean;
    environment: string;
  };
  warnings: string[];
  business: { name: string; website: string; services: string[] };
};

function Toggle({
  id,
  label,
  description,
  checked,
  onChange,
  disabled,
  warn,
}: {
  id: string;
  label: string;
  description: string;
  checked: boolean;
  onChange: (value: boolean) => void;
  disabled?: boolean;
  warn?: boolean;
}) {
  return (
    <div className="flex items-start justify-between gap-4 py-4 first:pt-0 last:pb-0">
      <div className="min-w-0">
        <label htmlFor={id} className="text-sm font-medium text-ink-900">
          {label}
        </label>
        <p className="mt-0.5 text-[0.8125rem] leading-relaxed text-ink-500">{description}</p>
      </div>
      <button
        id={id}
        type="button"
        role="switch"
        aria-checked={checked}
        disabled={disabled}
        onClick={() => onChange(!checked)}
        className={`relative mt-0.5 h-6 w-11 shrink-0 rounded-full transition-colors duration-200 after:absolute after:-inset-y-2.5 after:-inset-x-1 after:content-[''] disabled:opacity-50 ${
          checked ? (warn ? 'bg-warning-600' : 'bg-brand-600') : 'bg-ink-300'
        }`}
      >
        <span
          className={`absolute top-0.5 h-5 w-5 rounded-full bg-white shadow-xs transition-transform duration-200 ${
            checked ? 'translate-x-[1.375rem]' : 'translate-x-0.5'
          }`}
        />
      </button>
    </div>
  );
}

function ConfigRow({ label, ready, note }: { label: string; ready: boolean; note: string }) {
  return (
    <li className="flex flex-wrap items-center justify-between gap-x-3 gap-y-1.5 py-3 first:pt-0 last:pb-0">
      <div className="min-w-0 flex-1">
        <code className="text-[0.8125rem] font-medium text-ink-800">{label}</code>
        <p className="mt-0.5 text-xs leading-relaxed text-ink-500">{note}</p>
      </div>
      <Badge tone={ready ? 'success' : 'warning'} dot>
        {ready ? 'Configured' : 'Not set'}
      </Badge>
    </li>
  );
}

export default function SettingsClient() {
  const router = useRouter();
  const [payload, setPayload] = useState<Payload | null>(null);
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [flash, setFlash] = useState<string | null>(null);

  const load = useCallback(async () => {
    try {
      const response = await api.get<Payload>('/api/settings');
      setPayload(response.data);
      setError(null);
    } catch (caught) {
      setError(caught instanceof ApiError ? caught.message : 'Could not load your settings.');
    } finally {
      setLoading(false);
    }
  }, []);

  const refresh = useCallback(() => {
    setLoading(true);
    void load();
  }, [load]);

  useEffect(() => {
    void load();
  }, [load]);

  async function patch(update: Record<string, unknown>) {
    setBusy(true);
    setError(null);
    setFlash(null);
    try {
      const response = await api.patch<{ settings: Payload['settings'] }>('/api/settings', update);
      setFlash(response.message);
      await load();
    } catch (caught) {
      setError(caught instanceof ApiError ? caught.message : 'Could not save that change.');
    } finally {
      setBusy(false);
    }
  }

  async function signOut() {
    await api.post('/api/auth/logout').catch(() => undefined);
    router.replace('/login');
    router.refresh();
  }

  return (
    <>
      <PageHeader
        eyebrow="Configuration"
        title="Settings"
        description="How the automation behaves, and what is still waiting to be set up."
        action={
          <Button variant="secondary" onClick={refresh} loading={loading} icon={<RefreshIcon size={16} />}>
            Refresh
          </Button>
        }
      />

      {error ? (
        <div className="mb-4">
          <Callout tone="danger" title="Something went wrong">
            <p>{error}</p>
          </Callout>
        </div>
      ) : null}
      {flash ? (
        <div className="mb-4">
          <Callout tone="success" title="Saved" icon={<CheckCircleIcon size={18} />}>
            <p>{flash}</p>
          </Callout>
        </div>
      ) : null}

      {loading && !payload ? <SkeletonCard lines={5} /> : null}

      {payload ? (
        <div className="space-y-5">
          {payload.warnings.length > 0 ? (
            <Callout tone="warning" title="Still to set up" icon={<AlertIcon size={18} />}>
              <ul className="mt-1 list-disc space-y-1.5 pl-5">
                {payload.warnings.map((warning) => (
                  <li key={warning}>{warning}</li>
                ))}
              </ul>
            </Callout>
          ) : (
            <Callout tone="success" title="Everything is configured" icon={<CheckCircleIcon size={18} />}>
              <p>No outstanding setup steps. Your automation is running end to end.</p>
            </Callout>
          )}

          <Card>
            <SectionHeader
              title="Automation"
              description="These take effect on the next scheduled run"
              icon={<SparkIcon size={18} />}
              tone="ai"
            />
            <div className="divide-y divide-line">
              <Toggle
                id="auto-drafts"
                label="Draft replies automatically"
                description="When a sync finds a review without a reply, write a draft for it. You still approve every one."
                checked={payload.settings.autoGenerateDrafts}
                disabled={busy || !payload.config.aiConfigured}
                onChange={(value) => void patch({ autoGenerateDrafts: value })}
              />
              <Toggle
                id="auto-publish"
                label="Publish approved replies automatically"
                description="Off by design. Turning this on lets scheduled jobs publish approved drafts without a final look from you."
                checked={payload.settings.autoPublishReplies}
                disabled={busy}
                warn
                onChange={(value) => void patch({ autoPublishReplies: value })}
              />
            </div>

            <div className="mt-4 border-t border-line pt-4">
              <label htmlFor="min-stars" className="mb-1.5 block text-sm font-medium text-ink-900">
                Only draft replies for reviews rated
              </label>
              <select
                id="min-stars"
                value={payload.settings.autoDraftMinStars}
                disabled={busy}
                onChange={(event) => void patch({ autoDraftMinStars: Number(event.target.value) })}
                className="w-full rounded-xl border border-line bg-surface px-3.5 py-2.5 text-ink-900 outline-none transition-colors focus:border-brand-500 sm:max-w-xs"
              >
                {[1, 2, 3, 4, 5].map((stars) => (
                  <option key={stars} value={stars}>
                    {stars}★ and above
                  </option>
                ))}
              </select>
            </div>

            {!payload.config.aiConfigured ? (
              <p className="mt-3 rounded-xl bg-warning-50 px-3.5 py-2.5 text-xs leading-relaxed text-warning-700">
                OPENAI_API_KEY is not set, so drafting is unavailable regardless of these switches.
              </p>
            ) : null}
          </Card>

          <Card>
            <SectionHeader
              title="Configuration"
              description="Status only — no value is ever sent to your browser"
              icon={<ShieldIcon size={18} />}
              tone="brand"
              action={<Badge tone="neutral">{payload.config.environment}</Badge>}
            />
            <ul className="divide-y divide-line">
              <ConfigRow
                label="GOOGLE_CLIENT_ID / SECRET / REDIRECT_URI"
                ready={payload.config.oauthConfigured}
                note="OAuth client for the business.manage scope"
              />
              <ConfigRow
                label="GOOGLE_REFRESH_TOKEN"
                ready={payload.config.googleConfigured}
                note="Long-lived credential for the connected profile"
              />
              <ConfigRow
                label="OPENAI_API_KEY"
                ready={payload.config.aiConfigured}
                note="Required for AI reply drafting"
              />
              <ConfigRow
                label="CRON_SECRET"
                ready={payload.config.cronConfigured}
                note="Protects every scheduled job endpoint"
              />
              <ConfigRow
                label="ADMIN_PASSWORD / SESSION_SECRET"
                ready={payload.config.adminAuthConfigured}
                note="Locks this dashboard and all write APIs"
              />
              <ConfigRow
                label="UPSTASH_REDIS_REST_URL / TOKEN"
                ready={payload.config.durableStore}
                note="Durable storage for drafts, posts and the run log"
              />
              <ConfigRow
                label="GBP_ACCOUNT_NAME / GBP_LOCATION_NAME"
                ready={payload.config.pinnedLocation}
                note="Optional — pins the location instead of auto-detecting it"
              />
            </ul>
          </Card>

          <Card>
            <SectionHeader
              title="Business"
              description="Used to ground the tone and wording of AI reply drafts"
              icon={<SettingsIcon size={18} />}
              tone="neutral"
            />
            <div className="flex flex-wrap items-center justify-between gap-3">
              <div className="min-w-0">
                <p className="text-sm font-semibold text-ink-950">{payload.business.name}</p>
                <a
                  href={payload.business.website}
                  target="_blank"
                  rel="noreferrer noopener"
                  className="-ml-2 inline-flex min-h-9 items-center gap-1 rounded-lg px-2 text-[0.8125rem] text-brand-700 hover:bg-brand-50"
                >
                  {payload.business.website.replace(/^https?:\/\//, '')}
                  <ExternalIcon size={13} />
                </a>
              </div>
            </div>
            <div className="mt-4 flex flex-wrap gap-1.5 border-t border-line pt-4">
              {payload.business.services.map((service) => (
                <Badge key={service} tone="neutral">
                  {service}
                </Badge>
              ))}
            </div>
          </Card>

          {payload.config.adminAuthConfigured ? (
            <Card>
              <SectionHeader title="Session" description="You are signed in as the administrator" />
              <Button variant="secondary" icon={<LogoutIcon size={16} />} onClick={() => void signOut()}>
                Sign out
              </Button>
            </Card>
          ) : null}
        </div>
      ) : null}
    </>
  );
}

