'use client';

/**
 * Notification Center.
 *
 * Every notification is generated by a real event — a review synced, a draft
 * created, a post published, a Google API fault, a performance refresh. Never
 * decorative. "Open" follows the notification's own href, which is the same
 * place the underlying automation task would have sent you.
 */

import Link from 'next/link';
import { useCallback, useEffect, useState } from 'react';

import { api, ApiError, relativeTime } from '@/lib/client';
import {
  AlertIcon,
  CalendarIcon,
  ChartIcon,
  CheckIcon,
  ClockIcon,
  InboxIcon,
  LockIcon,
  PostIcon,
  RefreshIcon,
  SocialIcon,
  SparkIcon,
  StarIcon,
} from '@/components/icons';
import {
  Badge,
  Button,
  Callout,
  Card,
  EmptyState,
  PageHeader,
  SkeletonCard,
  TONE_SOFT,
  type Tone,
} from '@/components/ui';
import type { AppNotification, NotificationCategory } from '@/lib/types';

const CATEGORY_META: Record<NotificationCategory, { label: string; icon: React.ReactNode; tone: Tone }> = {
  new_review: { label: 'New review', icon: <StarIcon size={16} />, tone: 'warning' },
  ai_draft_ready: { label: 'AI draft ready', icon: <SparkIcon size={16} />, tone: 'ai' },
  post_scheduled: { label: 'Post scheduled', icon: <CalendarIcon size={16} />, tone: 'info' },
  post_published: { label: 'Post published', icon: <PostIcon size={16} />, tone: 'cyan' },
  google_api_issue: { label: 'Google API issue', icon: <AlertIcon size={16} />, tone: 'danger' },
  performance_report_ready: { label: 'Performance updated', icon: <ChartIcon size={16} />, tone: 'success' },
  profile_update: { label: 'Profile update', icon: <InboxIcon size={16} />, tone: 'neutral' },
  meta_connected: { label: 'Meta connected', icon: <SocialIcon size={16} />, tone: 'success' },
  meta_disconnected: { label: 'Meta disconnected', icon: <SocialIcon size={16} />, tone: 'neutral' },
  social_draft_created: { label: 'Social draft created', icon: <SparkIcon size={16} />, tone: 'ai' },
  social_post_approved: { label: 'Social post approved', icon: <CheckIcon size={16} />, tone: 'success' },
  social_post_scheduled: { label: 'Social post scheduled', icon: <CalendarIcon size={16} />, tone: 'info' },
  social_post_published: { label: 'Social post published', icon: <PostIcon size={16} />, tone: 'cyan' },
  social_post_failed: { label: 'Social post failed', icon: <AlertIcon size={16} />, tone: 'danger' },
  social_post_skipped: { label: 'Social post skipped', icon: <ClockIcon size={16} />, tone: 'warning' },
  meta_rate_limited: { label: 'Meta rate limited', icon: <ClockIcon size={16} />, tone: 'warning' },
  meta_token_expired: { label: 'Meta token expired', icon: <LockIcon size={16} />, tone: 'danger' },
  meta_permission_error: { label: 'Meta permission error', icon: <AlertIcon size={16} />, tone: 'danger' },
};

type Payload = { notifications: AppNotification[]; unread: number };

export default function NotificationsClient() {
  const [data, setData] = useState<Payload | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [busyId, setBusyId] = useState<string | null>(null);
  const [markingAll, setMarkingAll] = useState(false);

  const load = useCallback(async () => {
    try {
      const response = await api.get<Payload>('/api/notifications');
      setData(response.data);
      setError(null);
    } catch (caught) {
      setError(caught instanceof ApiError ? caught.message : 'Could not load notifications.');
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    void load();
  }, [load]);

  async function markOneRead(id: string) {
    setBusyId(id);
    try {
      await api.patch('/api/notifications', { id });
      await load();
    } catch {
      /* the next refresh will retry */
    } finally {
      setBusyId(null);
    }
  }

  async function markAll() {
    setMarkingAll(true);
    try {
      await api.patch('/api/notifications', { all: true });
      await load();
    } catch {
      /* the next refresh will retry */
    } finally {
      setMarkingAll(false);
    }
  }

  const notifications = data?.notifications ?? [];

  return (
    <>
      <PageHeader
        eyebrow="Stay on top of it"
        title="Notifications"
        description="Reviews, AI drafts, posts and Google API status, all in one feed."
        action={
          data && data.unread > 0 ? (
            <Button variant="secondary" onClick={() => void markAll()} loading={markingAll}>
              Mark all read
            </Button>
          ) : undefined
        }
      />

      {error ? (
        <div className="mb-4">
          <Callout tone="danger" title="Could not load notifications">
            <p>{error}</p>
          </Callout>
        </div>
      ) : null}

      {loading && !data ? (
        <SkeletonCard lines={5} />
      ) : notifications.length === 0 ? (
        <EmptyState
          icon={<InboxIcon size={22} />}
          tone="neutral"
          title="No notifications yet"
          description="They will appear here as reviews sync, drafts are generated, and posts publish."
        />
      ) : (
        <Card padded={false}>
          <ul className="divide-y divide-line">
            {notifications.map((notification) => {
              const meta = CATEGORY_META[notification.category];
              const body = (
                <div className="flex items-start gap-3 p-4">
                  <span
                    className={`flex h-9 w-9 shrink-0 items-center justify-center rounded-xl ${
                      notification.read ? 'bg-subtle text-ink-400' : TONE_SOFT[meta.tone]
                    }`}
                  >
                    {meta.icon}
                  </span>
                  <div className="min-w-0 flex-1">
                    <div className="flex flex-wrap items-center gap-2">
                      <p
                        className={`text-sm ${
                          notification.read ? 'font-medium text-ink-700' : 'font-semibold text-ink-950'
                        }`}
                      >
                        {notification.title}
                      </p>
                      {!notification.read ? <Badge tone={meta.tone}>New</Badge> : null}
                    </div>
                    <p className="mt-0.5 text-[0.8125rem] leading-relaxed text-ink-600">
                      {notification.message}
                    </p>
                    <p className="mt-1.5 text-xs text-ink-400">{relativeTime(notification.createdAt)}</p>
                  </div>
                  {!notification.read ? (
                    <button
                      type="button"
                      onClick={(event) => {
                        event.preventDefault();
                        void markOneRead(notification.id);
                      }}
                      disabled={busyId === notification.id}
                      aria-label="Mark read"
                      className="press flex h-8 w-8 shrink-0 items-center justify-center rounded-lg text-ink-400 hover:bg-subtle hover:text-ink-700"
                    >
                      {busyId === notification.id ? (
                        <RefreshIcon size={15} className="animate-spin" />
                      ) : (
                        <CheckIcon size={15} />
                      )}
                    </button>
                  ) : null}
                </div>
              );

              return (
                <li key={notification.id}>
                  {notification.href ? (
                    <Link href={notification.href} className="block hover:bg-subtle/60">
                      {body}
                    </Link>
                  ) : (
                    body
                  )}
                </li>
              );
            })}
          </ul>
        </Card>
      )}
    </>
  );
}
