/**
 * Runtime settings.
 *
 * Returns booleans and resource names only — never a credential. The response
 * includes the non-sensitive config summary so the dashboard can show exactly
 * which environment variables are still missing without ever seeing a value.
 */

import { z } from 'zod';

import { actorFromRequest, recordAudit } from '@/lib/audit';
import { configSummary, configWarnings, SERVICES, BUSINESS } from '@/lib/config';
import { describeAccess, readAccess } from '@/lib/gbp-access';
import { getRefreshToken } from '@/lib/google-auth';
import { getSettings, saveSettings } from '@/lib/repository';
import { assertAdmin, handleRoute, ok, parseJson } from '@/lib/security';

export const dynamic = 'force-dynamic';
export const runtime = 'nodejs';

const patchSchema = z.object({
  selectedAccount: z.string().trim().max(200).optional(),
  selectedLocation: z.string().trim().max(200).optional(),
  autoPublishReplies: z.boolean().optional(),
  autoGenerateDrafts: z.boolean().optional(),
  autoDraftMinStars: z.number().int().min(1).max(5).optional(),
});

export async function GET(request: Request) {
  return handleRoute('settings', async () => {
    assertAdmin(request);
    const refreshToken = await getRefreshToken().catch(() => null);
    // Read from the cached access record — this must not trigger a Google call.
    const access = await readAccess();
    return ok({
      settings: await getSettings(),
      config: configSummary(refreshToken),
      warnings: configWarnings(refreshToken),
      business: { ...BUSINESS, services: SERVICES },
      gbpAccess: {
        status: access.status,
        message: describeAccess(access.status),
        checkedAt: access.checkedAt,
      },
    });
  });
}

export async function PATCH(request: Request) {
  return handleRoute('settings', async () => {
    assertAdmin(request);
    const patch = await parseJson(request, patchSchema);
    const settings = await saveSettings(patch);
    await recordAudit({
      actor: actorFromRequest(request),
      action: 'settings_updated',
      resource: 'app-settings',
      status: 'success',
      source: 'dashboard',
      detail: Object.keys(patch).join(', '),
    });
    return ok(
      { settings },
      patch.autoPublishReplies === true
        ? 'Saved. Auto-publishing is now ON — approved replies can go live without review.'
        : 'Settings saved.',
    );
  });
}
