/**
 * Runtime settings.
 *
 * Returns booleans and resource names only — never a credential. The response
 * includes the non-sensitive config summary so the dashboard can show exactly
 * which environment variables are still missing without ever seeing a value.
 */

import { z } from 'zod';

import { actorFromRequest, recordAudit } from '@/lib/audit';
import { BUSINESS, configSummary, configWarnings, env, SERVICES } from '@/lib/config';
import { ensureAccessChecked, getLocationTitle } from '@/lib/connection';
import { AppError } from '@/lib/errors';
import { getCredentialState } from '@/lib/google-auth';
import { normalizeAccountName, parseLocationId } from '@/lib/google-business';
import { getSettings, latestRuns, saveSettings, type AppSettings } from '@/lib/repository';
import { assertAdmin, handleRoute, ok, parseJson } from '@/lib/security';
import { pingStore } from '@/lib/store';

export const dynamic = 'force-dynamic';
export const runtime = 'nodejs';
export const maxDuration = 60;

const ACCOUNT_RE = /^accounts\/[A-Za-z0-9_.-]+$/;
const LOCATION_RE = /^(accounts\/[A-Za-z0-9_.-]+\/)?locations\/[A-Za-z0-9_.-]+$/;

const patchSchema = z.object({
  selectedAccount: z.string().trim().max(200).regex(ACCOUNT_RE, 'Not a valid account name').optional(),
  selectedLocation: z.string().trim().max(200).regex(LOCATION_RE, 'Not a valid location name').optional(),
  autoPublishReplies: z.boolean().optional(),
  autoGenerateDrafts: z.boolean().optional(),
  autoDraftMinStars: z.number().int().min(1).max(5).optional(),
});

export async function GET(request: Request) {
  return handleRoute('settings', async () => {
    assertAdmin(request);
    const credential = await getCredentialState();
    // The same self-healing read the dashboard uses, so Settings can never show
    // "Pending" for a connection the dashboard already knows is working.
    const access = await ensureAccessChecked();
    const [storeReachable, runs] = await Promise.all([pingStore(), latestRuns()]);
    return ok({
      settings: await getSettings(),
      config: configSummary(credential.connected),
      warnings: configWarnings(credential.connected),
      business: { ...BUSINESS, services: SERVICES },
      credential,
      gbpAccess: access,
      // Facts the setup checklist needs to avoid claiming "done" for something
      // that is merely configured: is the store answering, and did cron run?
      runtime: {
        storeReachable,
        lastCronRunAt: runs[0]?.startedAt ?? null,
        cronFailed: runs.some((run) => !run.ok && run.details?.status !== 'skipped'),
      },
    });
  });
}

export async function PATCH(request: Request) {
  return handleRoute('settings', async () => {
    assertAdmin(request);
    const body = await parseJson(request, patchSchema);

    // AUTO_PUBLISH_REPLIES is the master switch. With it off, this toggle cannot
    // be turned on — otherwise the "off" in the environment would mean nothing.
    if (body.autoPublishReplies === true && !env().AUTO_PUBLISH_REPLIES) {
      throw new AppError(
        'CONFLICT',
        'Automatic publishing is locked off by AUTO_PUBLISH_REPLIES=false in the environment. Set it to true there first if you really want this.',
        409,
      );
    }

    const current = await getSettings();
    const patch: Partial<AppSettings> = { ...body };

    // The account and location are a pair. Changing the account while keeping the
    // old location would aim reviews and posts at a location that account does
    // not own, so the location is cleared unless it is chosen in the same call.
    if (body.selectedAccount) {
      const account = normalizeAccountName(body.selectedAccount);
      patch.selectedAccount = account;
      if (account !== current.selectedAccount && !body.selectedLocation) {
        patch.selectedLocation = undefined;
        patch.selectedLocationTitle = undefined;
      }
    }
    if (body.selectedLocation) {
      const location = `locations/${parseLocationId(body.selectedLocation)}`;
      patch.selectedLocation = location;
      patch.selectedLocationTitle = await getLocationTitle(location, {});
    }

    const settings = await saveSettings(patch);
    await recordAudit({
      actor: actorFromRequest(request),
      action: 'settings_updated',
      resource: 'app-settings',
      status: 'success',
      source: 'dashboard',
      detail: Object.keys(body).join(', '),
    });
    return ok(
      { settings },
      body.autoPublishReplies === true
        ? 'Saved. Auto-publishing is now ON — approved replies can go live without review.'
        : 'Settings saved.',
    );
  });
}
