/**
 * Persistence for everything the automation owns: reply drafts, Business
 * Profile posts, cached reviews and the automation run log.
 *
 * Backed by lib/store.ts, so it is durable when Upstash is configured and
 * in-memory otherwise.
 */

import { randomUUID } from 'node:crypto';

import { getStore, nsKey, readCollection } from './store';
import type {
  AutomationRun,
  AutomationRunName,
  GbpPost,
  PerformanceSnapshot,
  ReplyDraft,
  Review,
} from './types';

const DRAFT_PREFIX = nsKey('draft', '');
const POST_PREFIX = nsKey('post', '');
const REVIEWS_CACHE_KEY = nsKey('cache', 'reviews');
const PERFORMANCE_CACHE_KEY = nsKey('cache', 'performance');
const RUNS_KEY = nsKey('automation', 'runs');
const SETTINGS_KEY = nsKey('settings', 'app');

export function newId(): string {
  return randomUUID();
}

function nowIso(): string {
  return new Date().toISOString();
}

/* --------------------------------- drafts -------------------------------- */

function draftKey(id: string): string {
  return `${DRAFT_PREFIX}${id}`;
}

export async function listDrafts(): Promise<ReplyDraft[]> {
  const drafts = await readCollection<ReplyDraft>(DRAFT_PREFIX);
  return drafts.sort((a, b) => b.createdAt.localeCompare(a.createdAt));
}

export async function getDraft(id: string): Promise<ReplyDraft | null> {
  return getStore().get<ReplyDraft>(draftKey(id));
}

export async function findDraftByReviewId(reviewId: string): Promise<ReplyDraft | null> {
  const drafts = await listDrafts();
  return drafts.find((d) => d.reviewId === reviewId) ?? null;
}

export async function saveDraft(draft: ReplyDraft): Promise<ReplyDraft> {
  const updated: ReplyDraft = { ...draft, updatedAt: nowIso() };
  await getStore().set(draftKey(draft.id), updated);
  return updated;
}

export async function deleteDraft(id: string): Promise<void> {
  await getStore().del(draftKey(id));
}

/* --------------------------------- posts --------------------------------- */

function postKey(id: string): string {
  return `${POST_PREFIX}${id}`;
}

export async function listPosts(): Promise<GbpPost[]> {
  const posts = await readCollection<GbpPost>(POST_PREFIX);
  return posts.sort((a, b) => b.createdAt.localeCompare(a.createdAt));
}

export async function getPost(id: string): Promise<GbpPost | null> {
  return getStore().get<GbpPost>(postKey(id));
}

export async function savePost(post: GbpPost): Promise<GbpPost> {
  const updated: GbpPost = { ...post, updatedAt: nowIso() };
  await getStore().set(postKey(post.id), updated);
  return updated;
}

export async function deletePost(id: string): Promise<void> {
  await getStore().del(postKey(id));
}

/** Scheduled posts whose time has come and that have not been published. */
export async function listDuePosts(at: Date = new Date()): Promise<GbpPost[]> {
  const posts = await listPosts();
  return posts.filter(
    (p) => p.status === 'scheduled' && p.scheduledFor != null && new Date(p.scheduledFor) <= at,
  );
}

/* ----------------------------- review cache ------------------------------ */

export type ReviewCache = {
  reviews: Review[];
  averageRating: number | null;
  totalReviewCount: number;
  fetchedAt: string;
  locationPath: string;
};

export async function getCachedReviews(): Promise<ReviewCache | null> {
  return getStore().get<ReviewCache>(REVIEWS_CACHE_KEY);
}

export async function setCachedReviews(cache: ReviewCache): Promise<void> {
  await getStore().set(REVIEWS_CACHE_KEY, cache);
}

export async function getCachedPerformance(): Promise<PerformanceSnapshot | null> {
  return getStore().get<PerformanceSnapshot>(PERFORMANCE_CACHE_KEY);
}

export async function setCachedPerformance(snapshot: PerformanceSnapshot): Promise<void> {
  await getStore().set(PERFORMANCE_CACHE_KEY, snapshot);
}

/* ------------------------------ automation log --------------------------- */

const MAX_RUNS_KEPT = 40;

export async function listRuns(): Promise<AutomationRun[]> {
  return (await getStore().get<AutomationRun[]>(RUNS_KEY)) ?? [];
}

export async function recordRun(run: AutomationRun): Promise<void> {
  const runs = await listRuns();
  runs.unshift(run);
  await getStore().set(RUNS_KEY, runs.slice(0, MAX_RUNS_KEPT));
}

export async function lastRunOf(task: AutomationRunName): Promise<AutomationRun | null> {
  const runs = await listRuns();
  return runs.find((r) => r.task === task) ?? null;
}

/* -------------------------------- settings ------------------------------- */

export type AppSettings = {
  /** Account/location chosen in the dashboard; env pins override these. */
  selectedAccount?: string;
  selectedLocation?: string;
  /** Mirrors AUTO_PUBLISH_REPLIES but toggleable at runtime. Off by default. */
  autoPublishReplies: boolean;
  /** Generate drafts automatically when cron finds unanswered reviews. */
  autoGenerateDrafts: boolean;
  /** Ratings the automation is allowed to auto-draft for. */
  autoDraftMinStars: number;
  updatedAt: string;
};

export const DEFAULT_SETTINGS: AppSettings = {
  autoPublishReplies: false,
  autoGenerateDrafts: true,
  autoDraftMinStars: 1,
  updatedAt: new Date(0).toISOString(),
};

export async function getSettings(): Promise<AppSettings> {
  const stored = await getStore().get<AppSettings>(SETTINGS_KEY);
  return { ...DEFAULT_SETTINGS, ...(stored ?? {}) };
}

export async function saveSettings(patch: Partial<AppSettings>): Promise<AppSettings> {
  const current = await getSettings();
  const next: AppSettings = { ...current, ...patch, updatedAt: nowIso() };
  await getStore().set(SETTINGS_KEY, next);
  return next;
}
