/**
 * Automation tasks.
 *
 * These are the units of work the cron endpoints run. They are plain functions
 * so they can also be triggered manually from the dashboard, and every one of
 * them records an AutomationRun for the Automation Status page.
 *
 * Safety: publishReplies() only ever touches drafts an admin has explicitly
 * approved, and only when auto-publish is switched on. Generating a draft never
 * publishes anything.
 */

import { generateReplyDraft } from './ai-reply';
import { env, isAiConfigured } from './config';
import { resolveTarget } from './connection';
import { AppError } from './errors';
import { createLocalPost, fetchPerformance, listReviews, publishReviewReply } from './google-business';
import { log } from './logger';
import {
  findDraftByReviewId,
  getSettings,
  listDrafts,
  listDuePosts,
  newId,
  recordRun,
  saveDraft,
  savePost,
  setCachedPerformance,
  setCachedReviews,
} from './repository';
import type { AutomationRun, AutomationRunName, ReplyDraft, Review } from './types';

type TaskResult = Omit<AutomationRun, 'task' | 'startedAt' | 'finishedAt'>;

/** Runs a task, records the outcome, and never lets it throw past the caller. */
async function runTask(task: AutomationRunName, fn: () => Promise<TaskResult>): Promise<AutomationRun> {
  const startedAt = new Date().toISOString();
  let result: TaskResult;

  try {
    result = await fn();
  } catch (error) {
    const message =
      error instanceof AppError ? error.message : 'Unexpected failure while running the task.';
    if (!(error instanceof AppError)) {
      log.error('tasks', `Task ${task} crashed`, {
        error: error instanceof Error ? error.message : String(error),
      });
    }
    result = {
      ok: false,
      summary: message,
      details: { code: error instanceof AppError ? error.code : 'INTERNAL' },
    };
  }

  const run: AutomationRun = { task, startedAt, finishedAt: new Date().toISOString(), ...result };
  await recordRun(run).catch(() => {
    /* the run log is best-effort; never fail a task because of it */
  });
  return run;
}

/* ------------------------------ sync reviews ----------------------------- */

/**
 * Merges the live Google reviews with our local draft state so the dashboard
 * can show one coherent reply status per review.
 */
export function applyDraftStatus(reviews: Review[], drafts: ReplyDraft[]): Review[] {
  const byReviewId = new Map(drafts.map((d) => [d.reviewId, d]));
  return reviews.map((review) => {
    if (review.existingReply) return review;
    const draft = byReviewId.get(review.reviewId);
    if (!draft) return review;
    return { ...review, replyStatus: draft.status };
  });
}

export async function syncReviews(): Promise<AutomationRun> {
  return runTask('sync-reviews', async (): Promise<TaskResult> => {
    const target = await resolveTarget();
    const result = await listReviews(target.locationPath);
    const drafts = await listDrafts();

    await setCachedReviews({
      reviews: applyDraftStatus(result.reviews, drafts),
      averageRating: result.averageRating,
      totalReviewCount: result.totalReviewCount,
      fetchedAt: new Date().toISOString(),
      locationPath: target.locationPath,
    });

    const unanswered = result.reviews.filter((r) => !r.existingReply).length;
    return {
      ok: true,
      summary: `Synced ${result.reviews.length} reviews (${unanswered} without a reply on Google).`,
      details: { fetched: result.reviews.length, unanswered },
    };
  });
}

/* ---------------------------- generate drafts ---------------------------- */

/** How many drafts one cron invocation may generate, to bound cost and time. */
const MAX_DRAFTS_PER_RUN = 10;

export async function generateDrafts(): Promise<AutomationRun> {
  return runTask('generate-drafts', async (): Promise<TaskResult> => {
    if (!isAiConfigured()) {
      throw new AppError(
        'AI_NOT_CONFIGURED',
        'GROQ_API_KEY is not set, so no reply drafts can be generated.',
        503,
      );
    }

    const settings = await getSettings();
    if (!settings.autoGenerateDrafts) {
      return { ok: true, summary: 'Automatic draft generation is turned off in Settings.' };
    }

    const target = await resolveTarget();
    const { reviews } = await listReviews(target.locationPath, { maxPages: 2 });

    const candidates = reviews.filter(
      (review) => !review.existingReply && review.starRating >= settings.autoDraftMinStars,
    );

    let created = 0;
    let skipped = 0;
    let failed = 0;

    for (const review of candidates) {
      if (created >= MAX_DRAFTS_PER_RUN) break;
      if (await findDraftByReviewId(review.reviewId)) {
        skipped += 1;
        continue;
      }
      try {
        const draft = await createDraftForReview(review);
        await saveDraft(draft);
        created += 1;
      } catch (error) {
        failed += 1;
        log.warn('tasks', 'Could not draft a reply for a review', {
          reviewId: review.reviewId,
          error: error instanceof Error ? error.message : String(error),
        });
      }
    }

    return {
      ok: failed === 0,
      summary: `Created ${created} reply draft(s); ${skipped} already had one; ${failed} failed.`,
      details: { created, skipped, failed, candidates: candidates.length },
    };
  });
}

/** Builds (but does not persist) a draft for a review. */
export async function createDraftForReview(review: Review): Promise<ReplyDraft> {
  const generated = await generateReplyDraft(review);
  const now = new Date().toISOString();
  return {
    id: newId(),
    reviewId: review.reviewId,
    reviewName: review.name,
    reviewerName: review.reviewerName,
    starRating: review.starRating,
    reviewComment: review.comment,
    generatedText: generated.text,
    text: generated.text,
    language: generated.language,
    status: 'draft_pending',
    model: generated.model,
    createdAt: now,
    updatedAt: now,
  };
}

/* ---------------------------- publish replies ---------------------------- */

/**
 * Publishes replies that an admin has already approved.
 *
 * This is deliberately gated twice: the draft must be in `approved` state AND
 * auto-publishing must be enabled. With auto-publish off (the default) approved
 * drafts wait for the admin to press Publish in the dashboard.
 */
export async function publishApprovedReplies(): Promise<AutomationRun> {
  return runTask('sync-reviews', async (): Promise<TaskResult> => {
    const settings = await getSettings();
    const autoPublish = settings.autoPublishReplies || env().AUTO_PUBLISH_REPLIES;
    if (!autoPublish) {
      return {
        ok: true,
        summary: 'Auto-publishing is off — approved replies are waiting for manual publish.',
        details: { autoPublish: false },
      };
    }

    const drafts = (await listDrafts()).filter((d) => d.status === 'approved');
    let published = 0;
    let failed = 0;

    for (const draft of drafts) {
      try {
        await publishReviewReply(draft.reviewName, draft.text);
        await saveDraft({
          ...draft,
          status: 'published',
          publishedAt: new Date().toISOString(),
          error: undefined,
        });
        published += 1;
      } catch (error) {
        failed += 1;
        await saveDraft({
          ...draft,
          status: 'publish_failed',
          error: error instanceof AppError ? error.message : 'Publishing failed.',
        });
      }
    }

    return {
      ok: failed === 0,
      summary: `Auto-published ${published} approved repl${published === 1 ? 'y' : 'ies'}; ${failed} failed.`,
      details: { published, failed },
    };
  });
}

/* --------------------------- publish due posts --------------------------- */

export async function publishScheduledPosts(): Promise<AutomationRun> {
  return runTask('publish-posts', async (): Promise<TaskResult> => {
    const due = await listDuePosts();
    if (due.length === 0) {
      return { ok: true, summary: 'No scheduled posts were due.', details: { due: 0 } };
    }

    const target = await resolveTarget();
    let published = 0;
    let failed = 0;

    for (const post of due) {
      await savePost({ ...post, status: 'publishing' });
      try {
        const googlePostName = await createLocalPost(target.locationPath, post);
        await savePost({
          ...post,
          status: 'published',
          googlePostName,
          publishedAt: new Date().toISOString(),
          error: undefined,
        });
        published += 1;
      } catch (error) {
        failed += 1;
        // Stays 'failed', never 'published' — we do not claim a post went live.
        await savePost({
          ...post,
          status: 'failed',
          error: error instanceof AppError ? error.message : 'Publishing failed.',
        });
      }
    }

    return {
      ok: failed === 0,
      summary: `Published ${published} of ${due.length} due post(s); ${failed} failed.`,
      details: { due: due.length, published, failed },
    };
  });
}

/* --------------------------- sync performance ---------------------------- */

export async function syncPerformance(days = 30): Promise<AutomationRun> {
  return runTask('sync-performance', async (): Promise<TaskResult> => {
    const target = await resolveTarget();
    const snapshot = await fetchPerformance(target.locationName, { days });
    await setCachedPerformance(snapshot);

    const interactions = snapshot.series
      .filter((s) =>
        ['CALL_CLICKS', 'WEBSITE_CLICKS', 'BUSINESS_DIRECTION_REQUESTS', 'BUSINESS_CONVERSATIONS'].includes(
          s.metric,
        ),
      )
      .reduce((sum, s) => sum + s.total, 0);

    return {
      ok: true,
      summary: `Updated performance for ${snapshot.rangeStart} → ${snapshot.rangeEnd} (${interactions} interactions).`,
      details: { metrics: snapshot.series.length, interactions },
    };
  });
}
