'use client';

/**
 * Automation status.
 *
 * Cron endpoints are intentionally not triggerable from the browser: they need
 * CRON_SECRET, which never reaches client-side JavaScript. The page explains
 * that rather than offering a button that cannot work.
 */

import { useCallback, useEffect, useState } from 'react';

import { api, ApiError, relativeTime } from '@/lib/client';
import {
  AlertIcon,
  AutomationIcon,
  CalendarIcon,
  CheckCircleIcon,
  ChartIcon,
  LockIcon,
  RefreshIcon,
  SparkIcon,
  StarIcon,
} from '@/components/icons';
import {
  Badge,
  Button,
  Callout,
  Card,
  EmptyState,
  PageHeader,
  SectionHeader,
  SkeletonCard,
  StatusPill,
  type Tone,
} from '@/components/ui';
import type { DashboardSummary } from '@/lib/types';

const SCHEDULE = [
  {
    path: '/api/cron/sync',
    cron: '02:30 UTC daily',
    title: 'Daily sync',
    description: 'Pulls new reviews, drafts replies for anything unanswered, refreshes performance.',
    icon: <RefreshIcon size={18} />,
    tone: 'brand' as Tone,
  },
  {
    path: '/api/cron/publish-posts',
    cron: '03:30 UTC daily',
    title: 'Publish scheduled posts',
    description: 'Publishes any post whose scheduled time has passed.',
    icon: <CalendarIcon size={18} />,
    tone: 'info' as Tone,
  },
];

const TASK_META: Record<string, { label: string; icon: React.ReactNode; tone: Tone }> = {
  'sync-reviews': { label: 'Sync reviews', icon: <StarIcon size={16} />, tone: 'warning' },
  'generate-drafts': { label: 'Generate reply drafts', icon: <SparkIcon size={16} />, tone: 'ai' },
  'publish-posts': { label: 'Publish scheduled posts', icon: <CalendarIcon size={16} />, tone: 'info' },
  'publish-replies': { label: 'Auto-publish approved replies', icon: <CheckCircleIcon size={16} />, tone: 'success' },
  'sync-performance': { label: 'Update performance', icon: <ChartIcon size={16} />, tone: 'success' },
};

type SettingsPayload = {
  settings: { autoPublishReplies: boolean; autoGenerateDrafts: boolean; autoDraftMinStars: number };
  config: { cronConfigured: boolean; aiConfigured: boolean; durableStore: boolean };
};

export default function AutomationClient() {
  const [summary, setSummary] = useState<DashboardSummary | null>(null);
  const [settings, setSettings] = useState<SettingsPayload | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const load = useCallback(async () => {
    try {
      const [status, config] = await Promise.all([
        api.get<DashboardSummary>('/api/status'),
        api.get<SettingsPayload>('/api/settings'),
      ]);
      setSummary(status.data);
      setSettings(config.data);
      setError(null);
    } catch (caught) {
      setError(caught instanceof ApiError ? caught.message : 'Could not load automation status.');
    } finally {
      setLoading(false);
    }
  }, []);

  const refresh = useCallback(() => {
    setLoading(true);
    void load();
  }, [load]);

  useEffect(() => {
    void load();
  }, [load]);

  const cronReady = settings?.config.cronConfigured ?? false;

  return (
    <>
      <PageHeader
        eyebrow="Behind the scenes"
        title="Automation"
        description="What runs on a schedule, what it did last, and the safety switches around it."
        action={
          <Button variant="secondary" onClick={refresh} loading={loading} icon={<RefreshIcon size={16} />}>
            Refresh
          </Button>
        }
      />

      {error ? (
        <div className="mb-4">
          <Callout tone="danger" title="Could not load automation status">
            <p>{error}</p>
          </Callout>
        </div>
      ) : null}

      {loading && !settings ? <SkeletonCard lines={4} /> : null}

      {settings ? (
        <div className="space-y-5">
          {/* --------------------------- switches ------------------------ */}
          <div className="grid gap-3 sm:grid-cols-3">
            <Card>
              <p className="text-[0.8125rem] font-medium text-ink-500">Scheduled jobs</p>
              <div className="mt-2.5">
                <StatusPill tone={cronReady ? 'success' : 'danger'} pulse={cronReady}>
                  {cronReady ? 'Running' : 'Disabled'}
                </StatusPill>
              </div>
              <p className="mt-2.5 text-xs leading-relaxed text-ink-500">
                {cronReady
                  ? 'Authenticated with CRON_SECRET. Unauthenticated requests are rejected.'
                  : 'CRON_SECRET is not set, so every cron request is rejected.'}
              </p>
            </Card>

            <Card>
              <p className="text-[0.8125rem] font-medium text-ink-500">Auto-drafting</p>
              <div className="mt-2.5">
                <StatusPill tone={settings.settings.autoGenerateDrafts ? 'ai' : 'neutral'}>
                  {settings.settings.autoGenerateDrafts ? 'On' : 'Off'}
                </StatusPill>
              </div>
              <p className="mt-2.5 text-xs leading-relaxed text-ink-500">
                Drafts replies for reviews rated {settings.settings.autoDraftMinStars}★ and above.
              </p>
            </Card>

            <Card
              className={settings.settings.autoPublishReplies ? 'border-warning-200 bg-warning-50/40' : ''}
            >
              <p className="text-[0.8125rem] font-medium text-ink-500">Auto-publish replies</p>
              <div className="mt-2.5">
                <StatusPill tone={settings.settings.autoPublishReplies ? 'warning' : 'success'}>
                  {settings.settings.autoPublishReplies ? 'On — no human check' : 'Off'}
                </StatusPill>
              </div>
              <p className="mt-2.5 text-xs leading-relaxed text-ink-500">
                {settings.settings.autoPublishReplies
                  ? 'Approved replies can go live without you reviewing them again.'
                  : 'Approved replies wait for you to press Publish. Recommended.'}
              </p>
            </Card>
          </div>

          {!cronReady ? (
            <Callout tone="warning" title="Scheduled jobs are not running" icon={<AlertIcon size={18} />}>
              <p>
                Set <code className="font-medium">CRON_SECRET</code> in your environment and
                redeploy. Until then reviews are only synced when you open the dashboard and press
                Sync now.
              </p>
            </Callout>
          ) : null}

          {/* --------------------------- schedule ------------------------ */}
          <Card>
            <SectionHeader
              title="Schedule"
              description="Configured in vercel.json, shown in UTC"
              icon={<CalendarIcon size={18} />}
              tone="brand"
            />
            <ul className="divide-y divide-line">
              {SCHEDULE.map((job) => (
                <li key={job.path} className="flex items-start gap-3 py-3.5 first:pt-0 last:pb-0">
                  <span
                    className={`flex h-9 w-9 shrink-0 items-center justify-center rounded-xl ${
                      job.tone === 'brand' ? 'bg-brand-50 text-brand-700' : 'bg-info-50 text-info-700'
                    }`}
                  >
                    {job.icon}
                  </span>
                  <div className="min-w-0 flex-1">
                    <div className="flex flex-wrap items-center gap-2">
                      <p className="text-sm font-medium text-ink-900">{job.title}</p>
                      <Badge tone="neutral">{job.cron}</Badge>
                    </div>
                    <p className="mt-1 text-[0.8125rem] leading-relaxed text-ink-500">
                      {job.description}
                    </p>
                  </div>
                </li>
              ))}
            </ul>
            <p className="mt-3 border-t border-line pt-3 text-xs leading-relaxed text-ink-400">
              Two daily jobs keeps the project inside Vercel&apos;s Hobby plan limits. On Pro you can
              run them hourly — the README has the configuration.
            </p>
          </Card>

          {/* --------------------------- run log ------------------------- */}
          <Card>
            <SectionHeader
              title="Recent runs"
              description="Every scheduled and manual task records its outcome"
              icon={<AutomationIcon size={18} />}
              tone="brand"
            />
            {!summary || summary.automation.lastRuns.length === 0 ? (
              <EmptyState
                icon={<AutomationIcon size={22} />}
                tone="brand"
                compact
                title="No runs recorded yet"
                description="The log fills in after the first scheduled job fires, or when you press Sync now on the dashboard."
              />
            ) : (
              <ul className="divide-y divide-line">
                {summary.automation.lastRuns.map((run) => {
                  const meta = TASK_META[run.task] ?? {
                    label: run.task,
                    icon: <AutomationIcon size={16} />,
                    tone: 'neutral' as Tone,
                  };
                  return (
                    <li key={`${run.task}-${run.startedAt}`} className="flex items-start gap-3 py-3.5 first:pt-0 last:pb-0">
                      <span
                        className={`flex h-8 w-8 shrink-0 items-center justify-center rounded-lg ${
                          run.ok ? 'bg-success-50 text-success-700' : 'bg-danger-50 text-danger-700'
                        }`}
                      >
                        {run.ok ? <CheckCircleIcon size={16} /> : <AlertIcon size={16} />}
                      </span>
                      <div className="min-w-0 flex-1">
                        <div className="flex flex-wrap items-center justify-between gap-x-3 gap-y-1">
                          <p className="text-sm font-medium text-ink-900">{meta.label}</p>
                          <span className="shrink-0 text-xs text-ink-400">
                            {relativeTime(run.startedAt)}
                          </span>
                        </div>
                        <p className="mt-0.5 text-[0.8125rem] leading-relaxed text-ink-500">
                          {run.summary}
                        </p>
                      </div>
                    </li>
                  );
                })}
              </ul>
            )}
          </Card>

          {/* ------------------------ manual triggers -------------------- */}
          <Card>
            <SectionHeader
              title="Manual triggers"
              description="Run a job yourself from a terminal"
              icon={<LockIcon size={18} />}
              tone="neutral"
            />
            <div className="-mx-4 overflow-x-auto px-4 sm:mx-0 sm:px-0">
              <code className="block whitespace-pre rounded-xl bg-ink-950 px-3.5 py-3 text-xs leading-relaxed text-ink-200">
                {`curl -H "Authorization: Bearer $CRON_SECRET" \\\n  https://your-domain/api/cron/sync`}
              </code>
            </div>
            <ul className="mt-3 flex flex-wrap gap-1.5">
              {['sync', 'sync-reviews', 'generate-drafts', 'publish-posts', 'sync-performance'].map(
                (path) => (
                  <li key={path}>
                    <Badge tone="neutral">/api/cron/{path}</Badge>
                  </li>
                ),
              )}
            </ul>
            <p className="mt-3 text-xs leading-relaxed text-ink-400">
              CRON_SECRET is a server-only value that never reaches your browser, which is why these
              jobs cannot be triggered from this page.
            </p>
          </Card>
        </div>
      ) : null}
    </>
  );
}
