'use client';

/**
 * Automation status.
 *
 * Shows the cron schedule, the recent run log and the current safety switches.
 * Cron endpoints are not triggerable from the browser by design — they require
 * CRON_SECRET, which never reaches client-side JavaScript.
 */

import { useCallback, useEffect, useState } from 'react';

import { api, ApiError, relativeTime } from '@/lib/client';
import {
  Alert,
  Badge,
  Button,
  Card,
  CardHeader,
  EmptyState,
  LoadingCard,
  PageHeading,
} from '@/components/ui';
import type { DashboardSummary } from '@/lib/types';

const SCHEDULE = [
  {
    path: '/api/cron/sync',
    cron: '30 2 * * *',
    description: 'Sync reviews → draft replies → refresh performance',
  },
  {
    path: '/api/cron/publish-posts',
    cron: '30 3 * * *',
    description: 'Publish Business Profile posts whose scheduled time has passed',
  },
];

const MANUAL_ENDPOINTS = [
  '/api/cron/sync-reviews',
  '/api/cron/generate-drafts',
  '/api/cron/publish-posts',
  '/api/cron/sync-performance',
];

type SettingsPayload = {
  settings: {
    autoPublishReplies: boolean;
    autoGenerateDrafts: boolean;
    autoDraftMinStars: number;
  };
  config: { cronConfigured: boolean; aiConfigured: boolean; durableStore: boolean };
  warnings: string[];
};

export default function AutomationClient() {
  const [summary, setSummary] = useState<DashboardSummary | null>(null);
  const [settings, setSettings] = useState<SettingsPayload | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const load = useCallback(async () => {
    try {
      const [status, config] = await Promise.all([
        api.get<DashboardSummary>('/api/status'),
        api.get<SettingsPayload>('/api/settings'),
      ]);
      setSummary(status.data);
      setSettings(config.data);
      setError(null);
    } catch (caught) {
      setError(caught instanceof ApiError ? caught.message : 'Could not load automation status.');
    } finally {
      setLoading(false);
    }
  }, []);

  // `loading` starts as true, so the initial run needs no synchronous state
  // update — that is what keeps the effect below free of cascading renders.
  // Manual refreshes go through this wrapper instead.
  const refresh = useCallback(() => {
    setLoading(true);
    void load();
  }, [load]);

  useEffect(() => {
    void load();
  }, [load]);

  return (
    <>
      <PageHeading
        title="Automation Status"
        description="What runs on a schedule, and what it did last"
        action={
          <Button variant="secondary" size="sm" onClick={refresh} disabled={loading}>
            {loading ? 'Loading…' : 'Refresh'}
          </Button>
        }
      />

      {error ? (
        <div className="mb-4">
          <Alert tone="danger" title="Problem">
            <p>{error}</p>
          </Alert>
        </div>
      ) : null}

      {loading && !summary ? <LoadingCard lines={4} /> : null}

      {settings ? (
        <div className="mb-4 grid gap-3 sm:grid-cols-3">
          <Card>
            <p className="text-xs font-medium uppercase tracking-wide text-ink-500">Cron secret</p>
            <p className="mt-2">
              <Badge tone={settings.config.cronConfigured ? 'ok' : 'danger'}>
                {settings.config.cronConfigured ? 'Configured' : 'Missing'}
              </Badge>
            </p>
            <p className="mt-2 text-xs text-ink-500">
              {settings.config.cronConfigured
                ? 'Cron endpoints accept authenticated requests only.'
                : 'Cron endpoints reject every request until CRON_SECRET is set.'}
            </p>
          </Card>
          <Card>
            <p className="text-xs font-medium uppercase tracking-wide text-ink-500">Auto-drafting</p>
            <p className="mt-2">
              <Badge tone={settings.settings.autoGenerateDrafts ? 'ok' : 'neutral'}>
                {settings.settings.autoGenerateDrafts ? 'On' : 'Off'}
              </Badge>
            </p>
            <p className="mt-2 text-xs text-ink-500">
              Drafts replies for reviews rated {settings.settings.autoDraftMinStars}★ and above.
            </p>
          </Card>
          <Card>
            <p className="text-xs font-medium uppercase tracking-wide text-ink-500">
              Auto-publish replies
            </p>
            <p className="mt-2">
              <Badge tone={settings.settings.autoPublishReplies ? 'warn' : 'ok'}>
                {settings.settings.autoPublishReplies ? 'ON — no human check' : 'Off (recommended)'}
              </Badge>
            </p>
            <p className="mt-2 text-xs text-ink-500">
              While off, approved replies wait for you to press Publish.
            </p>
          </Card>
        </div>
      ) : null}

      <Card className="mb-4">
        <CardHeader title="Schedule" description="Configured in vercel.json (UTC)" />
        <ul className="divide-y divide-hairline">
          {SCHEDULE.map((entry) => (
            <li key={entry.path} className="py-3">
              <div className="flex flex-wrap items-center gap-2">
                <code className="rounded-lg bg-canvas px-2 py-1 text-xs text-ink-900">
                  {entry.path}
                </code>
                <Badge tone="brand">{entry.cron}</Badge>
              </div>
              <p className="mt-1 text-sm text-ink-500">{entry.description}</p>
            </li>
          ))}
        </ul>
        <p className="mt-3 text-xs text-ink-500">
          Two daily jobs keeps the project inside Vercel&apos;s Hobby plan limits. On Pro you can
          run them hourly — see the README.
        </p>
      </Card>

      <Card className="mb-4">
        <CardHeader
          title="Recent runs"
          description="Every cron and manual task records its outcome here"
        />
        {!summary || summary.automation.lastRuns.length === 0 ? (
          <EmptyState
            title="No runs recorded yet"
            description="The log fills up after the first cron firing."
          />
        ) : (
          <ul className="divide-y divide-hairline">
            {summary.automation.lastRuns.map((run) => (
              <li key={`${run.task}-${run.startedAt}`} className="py-3">
                <div className="flex flex-wrap items-center justify-between gap-2">
                  <div className="flex items-center gap-2">
                    <Badge tone={run.ok ? 'ok' : 'danger'}>{run.ok ? 'OK' : 'Failed'}</Badge>
                    <span className="text-sm font-medium text-ink-900">{run.task}</span>
                  </div>
                  <span className="text-xs text-ink-500">{relativeTime(run.startedAt)}</span>
                </div>
                <p className="mt-1 text-sm text-ink-700">{run.summary}</p>
              </li>
            ))}
          </ul>
        )}
      </Card>

      <Card>
        <CardHeader
          title="Manual triggers"
          description="Call these with your CRON_SECRET from a terminal — never from the browser"
        />
        <ul className="space-y-2">
          {MANUAL_ENDPOINTS.map((path) => (
            <li key={path}>
              <code className="block overflow-x-auto rounded-xl bg-canvas px-3 py-2 text-xs text-ink-700">
                curl -H &quot;Authorization: Bearer $CRON_SECRET&quot; https://your-domain{path}
              </code>
            </li>
          ))}
        </ul>
        <p className="mt-3 text-xs text-ink-500">
          CRON_SECRET is a server-only value. It is never sent to the browser, so these endpoints
          cannot be triggered from this page.
        </p>
      </Card>
    </>
  );
}
